name: CI on Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get toolchain repo
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - name: Update apt
      run: sudo apt update
    - name: Install gfortran-9
      run: sudo apt -y install gcc-9 gfortan-9
    - name: Add gfortran-7 as an alternative
      run: sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 7
    - name: Add gfortran-9 as an alternative
      run: sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-9 9
    - name: Install deps
      run: sudo apt -y install nco netcdf-bin
    - name: Build
      run: make -f makefile_gfortran
    - name: Test
      run: ctest
